### ISSUE TITLE
Return codes

### ISSUE THREAD

**Issue by mmihaltz** [numblr/nooj-cmd#1]
Could you please set the return code (exit status) to 1 (or anything non-0) when some kind of input error occurred, e.g. some of the specified files could not be opened, or a syntax error on the command line (actually I think the latter returns 1 now). Only successful execution should return 0.
Thanks! :)
Marci

**Comment by numblr** [comment]
Fixed in commit 3fba2fb53731b5795c78941a68d260e3eb74296b
